const path = require('path');
const React = require('react');
const express = require('express');
const ReactDOMServer = require('react-dom/server');
const Test = require('./test.js');
const generateIndex = require('./generateIndex.js');

const app = express();
const port = 3000;

// @TODO exclude autogenerated build/index.html file
app.use(express.static('build', {
  index: false,
}));
// app.use('/build', express.static('build'))

function handleRender(req, res) {
  const prerenderedHtml = ReactDOMServer.renderToString(<Test />);
  const html = generateIndex(prerenderedHtml, {});
  res.send(html);
  // res.sendfile('./build/index.html', { root: process.cwd() });
}

app.use(handleRender);

app.listen(port, () => console.log(`Example aspp listening on port ${port}!`));
